UPDATE distributions SET description = 'A simple, lightweight Linux distribution targeting competent Linux users.' WHERE slug = 'arch';
UPDATE distributions SET description = 'The universal operating system - a stable, secure, and versatile distribution committed to free software.' WHERE slug = 'debian';
UPDATE distributions SET description = 'An innovative platform for hardware, clouds, and containers - built on freedom, friends, features, and first.' WHERE slug = 'fedora';
UPDATE distributions SET description = 'A purely functional Linux distribution built on Nix package manager - reproducible, declarative configuration.' WHERE slug = 'nixos';
UPDATE distributions SET description = 'The leading OS for PCs, tablets, servers, and the cloud - user-friendly and accessible to all.' WHERE slug = 'ubuntu';
UPDATE distributions SET description = 'An Ubuntu-based distribution crafted for creators, makers, and computer builders by System76.' WHERE slug = 'popos';
UPDATE distributions SET description = 'A user-friendly Arch-based distribution for beginners and experienced users alike.' WHERE slug = 'manjaro';
UPDATE distributions SET description = 'An Arch-based distro providing a terminal-centric experience with a friendly installer and helpful community.' WHERE slug = 'endeavouros';
UPDATE distributions SET description = 'An elegant, easy-to-use desktop OS based on Ubuntu - designed for newcomers to Linux.' WHERE slug = 'mint';
UPDATE distributions SET description = 'A highly flexible source-based distribution for power users who want complete control and optimization.' WHERE slug = 'gentoo';
UPDATE distributions SET description = 'An independent Linux distribution emphasizing simplicity and avoiding unnecessary complexity.' WHERE slug = 'void';
UPDATE distributions SET description = 'A stable, multi-purpose distribution sponsored by SUSE, available in Leap and Tumbleweed variants.' WHERE slug = 'opensuse';
UPDATE distributions SET description = 'A beautiful, privacy-respecting, and user-friendly replacement for Windows and macOS.' WHERE slug = 'elementary';
UPDATE distributions SET description = 'An Arch-based gaming distribution with performance tweaks and gaming tools out of the box.' WHERE slug = 'garuda';
UPDATE distributions SET description = 'A Debian-based distribution designed for digital forensics, penetration testing, and security research.' WHERE slug = 'kali';
UPDATE distributions SET description = 'A security-oriented, lightweight distribution suitable for containers and secure systems.' WHERE slug = 'alpine';
UPDATE distributions SET description = 'A community enterprise OS compatible with RHEL, designed for production environments.' WHERE slug = 'rocky';
UPDATE distributions SET description = 'An open-source, community-driven RHEL fork designed for long-term stability and enterprise use.' WHERE slug = 'almalinux';
UPDATE distributions SET description = 'A security-focused desktop OS using virtualization-based isolation to enhance privacy and security.' WHERE slug = 'qubes';
UPDATE distributions SET description = 'An Arch-based distribution with performance optimizations, custom kernels, and GUI tools.' WHERE slug = 'cachyos';
UPDATE distributions SET description = 'An immutable Fedora-based gaming OS built on OCI containers for Steam Deck and desktop.' WHERE slug = 'bazzite';
UPDATE distributions SET description = 'An independent rolling-release distribution focused on desktop users with curated software.' WHERE slug = 'solus';
